### PR TITLE
Simplified controller

### PR DESCRIPTION
**Pull request by ivargrimstad**
Replaced xml-based validation config with annotation
Moved @Controller annotation to class level

### CODE REVIEW

**Comment by chkal** [comment]
Hey @ivargrimstad,

thanks a lot. I agree that @Controller should be moved to the class level.

However, I'm not so sure about replacing the validation XML config with annotations. I think that for MVC application configuring a **default** validation mode of NONE makes sense in most cases. If you don't do so, you will have to repeat the same annotation over and over again on every method that handles POST data. And IMO the annotation name is a bit confusing. The name could make people think that this will **skip** validation, but actually it **does** validate the input data, it just doesn't fail with an exception in case of violations.

Any thoughts on this? I would love to hear other opinions. That's why I created a first sample app to show how I would use the API, with doesn't mean that it is the best way. ;)

**Comment by ivargrimstad** [comment]
Totally agree that the annotation name is confusing!
But I kind of like the explicitness that you actually say that the input for the particular is validated in the code rather than have a configuration "hidden away in an xml file somewhere".
Just as I prefer bean-discovery-mode="annotated" in beans.xml (or no beans.xml at all) and explicitly annotate beans that should be injectable.

I guess it boils down to a matter of taste :)

**Comment by chkal** [comment]
Yeah, I agree. A matter of taste. :)
Perhaps the sample app should simply demonstrate that both ways are possible..

**Comment by ivargrimstad** [comment]
That is a good idea!

**Comment by chkal** [comment]
I just added validation.xml again and added a comment explaining that you can use it to change the default behavior. I think it is fine this way. :)

https://github.com/chkal/todo-mvc/blob/d9877c5532e8d6854d4e5874eda5fb36c431551c/src/main/resources/META-INF/validation.xml#L7-13

**Pull request merged**
